create database posts;
create extension pgcrypto;

create table users (
  user_id int generated by default as identity primary key,
  username varchar(32) not null,
  password varchar(60) not null,
  joined_at timestamp with time zone default current_timestamp
);

create unique index username_idx on users(lower(username));

create table posts (
  post_id int generated by default as identity primary key,
  post_title varchar(32) not null,
  post_content varchar (128) not null,
  user_id int not null references users(user_id)
);

create table comments (
  comment_id int generated by default as identity primary key,
  comment_content varchar(64) not null,
  user_id int not null references users(user_id),
  post_id int not null references posts(post_id)
);
